version: '3.3'

services: 
  chat-app:
    build: .
    image: node-mysql-app
    # ports:
    #  - 3100:3100
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-app
    ports:
      - "8080:8080"
# volumes:
# networks:
#   default:
#     driver: bridge
#     name: chat-app
